# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  catalogapi:
    image: ${REGISTRY:-eshoptraining}/catalogapi:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services\Catalog\Catalog.API\Dockerfile
    depends_on:
      - sqldata  

  sqldata:
    image: mcr.microsoft.com/mssql/server:latest