# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  catalog-api:
    image: ${REGISTRY:-odoya}/catalog-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services\Catalog\Catalog.API\Dockerfile
    depends_on:
      - mongo  

  mongo:
    image: mongo:5.0.4