name: catalogapi-build-and-test

on:
  push:
    branches: [ main, dev ]
    paths:
    - 'src\Services\Catalog\**.cs'
    - 'src\Services\Catalog\Catalog.UnitTests\Catalog.UnitTests.csproj'
    - 'src\Services\Catalog\Catalog.IntegrationTests\Catalog.IntegrationTests.csproj'
    - 'src\Services\Catalog\Catalog.API\Catalog.API.csproj'
  pull_request:
    branches: [ main ]
    paths:
    - 'src\Services\Catalog\**.cs'
    - 'src\Services\Catalog\Catalog.UnitTests\Catalog.UnitTests.csproj'
    - 'src\Services\Catalog\Catalog.IntegrationTests\Catalog.IntegrationTests.csproj'
    - 'src\Services\Catalog\Catalog.API\Catalog.API.csproj'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
