name: CatalogApi Build and Push Image

on:
  workflow_dispatch:

  push:
    branches: [main]
    tags:
      - "v*"
    # paths:
    #   - src/Services/Catalog/**
    #   - .github/workflows/catalogapi-image-build-and-push.yml

  pull_request:
    branches: [main]
    # paths:
    #   - src/Services/Catalog/**
    #   - .github/workflows/catalogapi-image-build-and-push.yml

  # workflow_run:
  #   workflows: ["CatalogApi Build and Test"]
  #   branches: [main]
  #   types: [completed]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: odoya/catalog-api
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request' || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./src
          file: src/Services/Catalog/Catalog.API/Dockerfile
          push: ${{ github.event_name != 'pull_request' || github.event_name == 'workflow_dispatch'}}
          tags: ${{ steps.meta.outputs.tags }}
